"""CRM tools — read-only access to insurance data stored in a DuckDB database.

The database is generated by ``generate_synthetic_data.py`` and contains
three tables: customers, policies, and claims.
"""

from __future__ import annotations

import json
import logging
import os
import pathlib
from datetime import date

import duckdb
from langchain_core.tools import tool

logger = logging.getLogger(__name__)

_DB_PATH = os.environ.get(
    "CRM_DB_PATH",
    str(pathlib.Path(__file__).resolve().parent.parent.parent / "insurance_data.db"),
)


def _get_conn() -> duckdb.DuckDBPyConnection:
    """Return a read-only DuckDB connection to the CRM database."""
    return duckdb.connect(_DB_PATH, read_only=True)


def _json_serial(obj: object) -> str:
    """JSON serializer for types not handled by default."""
    if isinstance(obj, date):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")


def _rows_to_dicts(cursor: duckdb.DuckDBPyConnection) -> list[dict]:
    """Convert DuckDB query results to a list of dicts."""
    cols = [desc[0] for desc in cursor.description]
    return [dict(zip(cols, row)) for row in cursor.fetchall()]


# ── Structured CRM tools ────────────────────────────────────────────────────


@tool
def crm_search_name(query: str) -> str:
    """Search insurance customers by name (case-insensitive, partial match).

    Args:
        query: Full or partial customer name to search for.

    Returns:
        JSON array of matching customer profiles with policy counts.
    """
    conn = _get_conn()
    try:
        results = _rows_to_dicts(
            conn.execute(
                """
                SELECT c.customer_id, c.first_name, c.last_name, c.email,
                       c.phone, c.date_of_birth, c.city, c.state,
                       COUNT(DISTINCT p.policy_id) AS total_policies,
                       COUNT(DISTINCT CASE WHEN p.status = 'active' THEN p.policy_id END) AS active_policies
                FROM customers c
                LEFT JOIN policies p ON c.customer_id = p.customer_id
                WHERE LOWER(c.first_name || ' ' || c.last_name) LIKE ?
                GROUP BY c.customer_id, c.first_name, c.last_name, c.email,
                         c.phone, c.date_of_birth, c.city, c.state
                LIMIT 20
                """,
                [f"%{query.lower()}%"],
            )
        )
        if not results:
            return json.dumps({"message": f"No customers found matching '{query}'."})
        return json.dumps(results, indent=2, default=_json_serial)
    finally:
        conn.close()


@tool
def crm_search_id(query: str) -> str:
    """Look up an insurance customer by their exact customer ID.

    Args:
        query: The customer ID to look up (integer as string).

    Returns:
        JSON object with customer profile, policy summaries, and claim summaries.
    """
    conn = _get_conn()
    try:
        cust = _rows_to_dicts(
            conn.execute("SELECT * FROM customers WHERE customer_id = ?", [int(query)])
        )
        if not cust:
            return json.dumps({"message": f"No customer found with ID '{query}'."})

        customer = cust[0]
        customer["policies"] = _rows_to_dicts(
            conn.execute(
                """SELECT policy_id, policy_type, coverage_amount, premium_amount,
                          start_date, end_date, status
                   FROM policies WHERE customer_id = ?""",
                [int(query)],
            )
        )
        customer["claims"] = _rows_to_dicts(
            conn.execute(
                """SELECT cl.claim_id, cl.policy_id, cl.claim_amount, cl.claim_date,
                          cl.claim_status, cl.claim_type
                   FROM claims cl
                   JOIN policies p ON cl.policy_id = p.policy_id
                   WHERE p.customer_id = ?""",
                [int(query)],
            )
        )
        return json.dumps(customer, indent=2, default=_json_serial)
    finally:
        conn.close()


@tool
def crm_get_policies(query: str) -> str:
    """Get full policy details for a customer by their customer ID.

    Args:
        query: The customer ID whose policies to retrieve.

    Returns:
        JSON array with complete policy objects including coverage details.
    """
    conn = _get_conn()
    try:
        results = _rows_to_dicts(
            conn.execute(
                "SELECT * FROM policies WHERE customer_id = ? ORDER BY start_date DESC",
                [int(query)],
            )
        )
        if not results:
            return json.dumps({"message": f"No policies found for customer ID '{query}'."})
        return json.dumps(results, indent=2, default=_json_serial)
    finally:
        conn.close()


@tool
def crm_list_customers() -> str:
    """List insurance customers with a brief summary of each (first 50).

    Returns:
        JSON array of customer summaries with policy counts.
    """
    conn = _get_conn()
    try:
        results = _rows_to_dicts(
            conn.execute(
                """
                SELECT c.customer_id, c.first_name, c.last_name, c.city, c.state,
                       COUNT(DISTINCT p.policy_id) AS total_policies,
                       COUNT(DISTINCT CASE WHEN p.status = 'active' THEN p.policy_id END) AS active_policies
                FROM customers c
                LEFT JOIN policies p ON c.customer_id = p.customer_id
                GROUP BY c.customer_id, c.first_name, c.last_name, c.city, c.state
                ORDER BY c.customer_id
                LIMIT 50
                """
            )
        )
        return json.dumps(results, indent=2, default=_json_serial)
    finally:
        conn.close()


# ── Analytics tool (natural language → SQL) ─────────────────────────────────

# Database schema description for the LLM
_DB_SCHEMA = """
Tables and Columns:

1. customers
   - customer_id (INTEGER, PRIMARY KEY)
   - first_name (VARCHAR)
   - last_name (VARCHAR)
   - email (VARCHAR)
   - phone (VARCHAR)
   - date_of_birth (DATE)
   - address (VARCHAR)
   - city (VARCHAR)
   - state (VARCHAR)
   - zip_code (VARCHAR)

2. policies
   - policy_id (INTEGER, PRIMARY KEY)
   - customer_id (INTEGER, FK → customers.customer_id)
   - policy_type (VARCHAR) — values: 'auto', 'home', 'life', 'travel'
   - coverage_amount (DECIMAL)
   - premium_amount (DECIMAL)
   - start_date (DATE)
   - end_date (DATE)
   - status (VARCHAR) — values: 'active', 'expired', 'cancelled', 'suspended'

3. claims
   - claim_id (INTEGER, PRIMARY KEY)
   - policy_id (INTEGER, FK → policies.policy_id)
   - claim_amount (DECIMAL)
   - claim_date (DATE)
   - claim_status (VARCHAR) — values: 'pending', 'approved', 'denied', 'processing'
   - claim_type (VARCHAR)
   - description (TEXT)
"""

_SQL_SYSTEM_PROMPT = f"""You are a SQL expert. Given a natural language question about
insurance data, generate a DuckDB-compatible SELECT query.

{_DB_SCHEMA}

Rules:
1. Only use tables and columns from the schema above.
2. Use DuckDB SQL syntax (YEAR(), MONTH(), etc. for date functions).
3. Use JOINs when data from multiple tables is needed.
4. Limit results to 20 rows unless the user specifies otherwise.
5. Return ONLY the SQL query — no explanation, no markdown fences."""

# Will be set by init_crm_tools() when the orchestrator passes the LLM
_llm = None


def init_crm_tools(llm: object) -> None:
    """Provide the LLM instance needed by the analytics tool."""
    global _llm
    _llm = llm


@tool
def crm_analytics(question: str) -> str:
    """Run a complex analytics query against the insurance CRM database.

    Converts a natural-language question into SQL and executes it against the
    DuckDB database containing customers, policies, and claims.

    Use this tool for aggregate queries, comparisons, trend analysis, or any
    question that the other CRM tools cannot answer directly.

    Args:
        question: A natural language question about insurance data.

    Returns:
        Formatted query results as a table string.
    """
    if _llm is None:
        return "Error: analytics LLM not initialized."

    from langchain_core.messages import HumanMessage, SystemMessage

    try:
        response = _llm.invoke(
            [SystemMessage(content=_SQL_SYSTEM_PROMPT), HumanMessage(content=question)]
        )
        sql_query = response.content.strip()

        # Strip markdown code fences if present
        if sql_query.startswith("```"):
            lines = sql_query.split("\n")
            sql_query = "\n".join(
                l for l in lines if not l.strip().startswith("```")
            ).strip()

        if not sql_query.upper().startswith("SELECT"):
            return f"Error: LLM generated a non-SELECT statement — refusing to execute.\n{sql_query}"

        conn = _get_conn()
        try:
            result = conn.execute(sql_query).fetchall()
            col_names = [desc[0] for desc in conn.description]
        finally:
            conn.close()

        if not result:
            return f"Query returned no results.\nSQL: {sql_query}"

        # Format as a readable table
        output = f"SQL: {sql_query}\n\n"
        output += " | ".join(col_names) + "\n"
        output += "-" * len(" | ".join(col_names)) + "\n"
        for row in result[:20]:
            formatted = []
            for item in row:
                if isinstance(item, float):
                    formatted.append(f"{item:,.2f}")
                elif isinstance(item, int):
                    formatted.append(f"{item:,}")
                elif isinstance(item, date):
                    formatted.append(item.isoformat())
                else:
                    formatted.append(str(item))
            output += " | ".join(formatted) + "\n"
        if len(result) > 20:
            output += f"\n... showing first 20 of {len(result)} total results"
        return output

    except Exception as e:
        return f"Error executing analytics query: {e}"


CRM_TOOLS = [crm_search_name, crm_search_id, crm_get_policies, crm_list_customers, crm_analytics]
